pipeline {
  agent none
  environment {
      NEXUS_REGISTRY_URL = "http://172.29.4.6:5000"
      NEXUS_DOCKER_REPOSITORY_URL = "${NEXUS_REGISTRY_URL}/repository/docker-internal"
      NEXUS_IMAGE_NAME = "docker-internal/jenkins-agents/jenkins-agent-jdk8"
      NEXUS_IMAGE_TAG = "latest"
  }
  stages {
    //stage('Docker Build') {
    //  agent any
    //  steps {
    //    sh 'docker build -t ${NEXUS_DOCKER_REPOSITORY_URL}/${NEXUS_IMAGE_NAME}:${NEXUS_IMAGE_TAG} jenkins-agent-maven-jdk8/'
    //  }
    //}

    stage('Docker Push') {
      agent any
      steps {
          script {
            /*def docker_daemon =
                      '''{
                            "insecure-registries": [
                               "http://nexus:5001"
                            ]
                      }'''
            writeFile file:"/etc/docker/daemon.json", text: docker_daemon
            sh "cat /etc/docker/daemon.json"*/
            docker.withRegistry("${NEXUS_REGISTRY_URL}", 'nexus-credentials') {
              def image = docker.build("${NEXUS_IMAGE_NAME}:${NEXUS_IMAGE_TAG}", "-f jenkins-agent-maven-jdk8/Dockerfile")
              image.push()
            }
          }
      }
    }
  }
}
