pipeline {
  agent none
  environment {
      NEXUS_IMAGE_NAME = "docker-internal/jenkins-agents/jenkins-agent-pwsh"
      NEXUS_IMAGE_TAG = "latest"
  }
  stages {
    stage('Docker Push') {
      agent any
      steps {
          script {
              def nexus_container_ip = sh(script: 'docker inspect -f "{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}" nexus', returnStdout: true).trim()
              def nexus_registry_url = "http://$nexus_container_ip/$env.NEXUS_IMAGE_NAME"
              sh "echo $nexus_registry_url"
            docker.withRegistry("$nexus_registry_url", 'nexus-credentials') {
              def image = docker.build("${NEXUS_IMAGE_NAME}:${NEXUS_IMAGE_TAG}", "jenkins-agent-pwsh/")
              image.push()
            }
          }
      }
    }
  }
}
