pipeline {
  agent none
  environment {
      def nexus_container_ip = sh(script: 'docker inspect -f "{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}" nexus', returnStdout: true)
      NEXUS_REGISTRY_URL = "$nexus_container_ip:5000"
      NEXUS_DOCKER_REPOSITORY_URL = "${NEXUS_REGISTRY_URL}/repository/docker-internal"
      NEXUS_IMAGE_NAME = "docker-internal/jenkins-agents/jenkins-agent-pwsh"
      NEXUS_IMAGE_TAG = "latest"
  }
  stages {
    stage('Docker Push') {
      agent any
      steps {
          script {
            docker.withRegistry("${NEXUS_REGISTRY_URL}", 'nexus-credentials') {
              def image = docker.build("${NEXUS_IMAGE_NAME}:${NEXUS_IMAGE_TAG}", "jenkins-agent-pwsh/")
              image.push()
            }
          }
      }
    }
  }
}
